plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Meta-Machina
description: A machine that creates and destroys machines.
